package com.example.ordermgmt.service.impl.order;

import com.example.ordermgmt.dto.BulkOrderFailureDTO;
import com.example.ordermgmt.dto.BulkOrderStatusUpdateDTO;
import com.example.ordermgmt.dto.BulkOrderUpdateResultDTO;
import com.example.ordermgmt.dto.OrderDTO;
import com.example.ordermgmt.dto.OrderItemDTO;
import com.example.ordermgmt.dto.OrderStatusUpdateDTO;
import com.example.ordermgmt.entity.Customer;
import com.example.ordermgmt.entity.OrderItem;
import com.example.ordermgmt.entity.Orders;
import com.example.ordermgmt.entity.OrderStatusLookup;
import com.example.ordermgmt.enums.OrderStatus;
import com.example.ordermgmt.exception.InsufficientStockException;
import com.example.ordermgmt.exception.InvalidOperationException;
import com.example.ordermgmt.exception.OrderNotFoundException;
import com.example.ordermgmt.repository.OrderItemRepository;
import com.example.ordermgmt.repository.OrdersRepository;
import com.example.ordermgmt.service.OrderService;
import com.example.ordermgmt.event.EmailDispatchEvent;
import org.springframework.context.ApplicationEventPublisher;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

import static java.util.stream.Collectors.groupingBy;

@Service
@RequiredArgsConstructor
public class OrderServiceImpl implements OrderService {

    private static final Logger logger = LoggerFactory.getLogger(OrderServiceImpl.class);

    private final OrdersRepository ordersRepository;
    private final OrderItemRepository orderItemRepository;
    private final OrderValidatorImpl orderValidator;
    private final OrderInventoryManagerImpl orderInventoryManager;
    private final OrderMapperImpl orderMapper;
    private final OrderTransitionHelper transitionHelper;
    private final ApplicationEventPublisher eventPublisher;

    @Override
    @Transactional
    public OrderDTO createOrder(OrderDTO request, String email) {
        logger.info("Processing createOrder for Customer: {}", email);

        Customer customer = orderValidator.validateAndGetCustomer(email);
        orderValidator.validateCustomerProfile(customer);

        OrderStatusLookup pendingStatus = orderValidator.getStatusOrThrow(OrderStatus.PENDING.name());

        Orders order = new Orders();
        // orderId is auto-generated by @UuidGenerator (UUID v7)
        order.setCustomer(customer);
        order.setStatus(pendingStatus);

        ordersRepository.saveAndFlush(order);
        logger.info("Order entity saved with ID: {}", order.getOrderId());

        List<OrderItemDTO> itemDTOs = orderInventoryManager.processAndSaveOrderItems(request.getItems(), order);

        BigDecimal total = orderMapper.calculateTotal(itemDTOs);
        // Items are already in memory from inventory processing — use the full overload
        // to avoid an extra query
        OrderDTO responseDTO = orderMapper.convertToDTO(order, itemDTOs, total);

        logger.info("createOrder completed successfully for Customer: {}", email);

        eventPublisher.publishEvent(new EmailDispatchEvent(
                email,
                "Order Receipt #" + order.getOrderId(),
                "order-receipt",
                customer.getOrgId(),
                java.util.Map.of(
                        "name", customer.getFirstName() != null
                                ? customer.getFirstName()
                                        + (customer.getLastName() != null ? " " + customer.getLastName() : "")
                                : customer.getAppUser().getEmail(),
                        "order", responseDTO,
                        "summary", "Your order has been placed successfully.")));

        return responseDTO;
    }

    @Override
    @Transactional(readOnly = true)
    public List<OrderDTO> getCustomerOrders(String email) {
        logger.info("Processing getCustomerOrders for Customer: {}", email);

        List<Orders> orders = ordersRepository.findByCustomerAppUserEmail(email);

        /*
         * Batch-fetch all order items for the full result set in a single
         * SELECT … WHERE order_id IN (…) query, then group them by order ID.
         * This eliminates the N+1 problem: without this, each call to
         * orderMapper.convertToDTO(order) would fire a separate DB query.
         */
        Map<UUID, List<OrderItem>> itemsByOrderId = fetchItemsMap(orders);

        List<OrderDTO> result = orders.stream()
                .map(order -> orderMapper.convertToDTO(order, itemsByOrderId))
                .collect(Collectors.toList());

        logger.info("getCustomerOrders completed successfully for Customer: {}", email);
        return result;
    }

    @Override
    @Transactional(readOnly = true)
    public Page<OrderDTO> getCustomerOrders(String email, Pageable pageable) {
        logger.info("Processing getCustomerOrders (Page) for Customer: {}", email);

        Page<Orders> page = ordersRepository.findByCustomerAppUserEmail(email, pageable);

        /*
         * Batch-fetch items only for the current page's orders.
         * Spring Data JPA pagination already limits the order query to the page size,
         * so the IN clause here stays small and bounded.
         */
        Map<UUID, List<OrderItem>> itemsByOrderId = fetchItemsMap(page.getContent());

        Page<OrderDTO> result = page.map(order -> orderMapper.convertToDTO(order, itemsByOrderId));

        logger.info("getCustomerOrders (Page) completed successfully for Customer: {}", email);
        return result;
    }

    @Override
    @Transactional(readOnly = true)
    public List<OrderDTO> getAllOrders() {
        logger.info("Processing getAllOrders for Admin");

        List<Orders> orders = ordersRepository.findAll();

        /*
         * Single batch query replaces N individual order-item queries.
         * Total DB round-trips for this endpoint: 2, regardless of result set size.
         */
        Map<UUID, List<OrderItem>> itemsByOrderId = fetchItemsMap(orders);

        List<OrderDTO> result = orders.stream()
                .map(order -> orderMapper.convertToDTO(order, itemsByOrderId))
                .collect(Collectors.toList());

        logger.info("getAllOrders completed successfully for Admin");
        return result;
    }

    @Override
    @Transactional(readOnly = true)
    public Page<OrderDTO> getAllOrders(Pageable pageable) {
        logger.info("Processing getAllOrders (Page) for Admin");

        Page<Orders> page = ordersRepository.findAll(pageable);

        Map<UUID, List<OrderItem>> itemsByOrderId = fetchItemsMap(page.getContent());

        Page<OrderDTO> result = page.map(order -> orderMapper.convertToDTO(order, itemsByOrderId));

        logger.info("getAllOrders (Page) completed successfully for Admin");
        return result;
    }

    @Override
    @Transactional(readOnly = true)
    public OrderDTO getCustomerOrderById(UUID orderId, String email) {
        logger.info("Processing getCustomerOrderById for Order: {}, Customer: {}", orderId, email);
        Orders order = getOrderOrThrow(orderId);

        orderValidator.validateOrderOwnership(order, email);

        logger.info("getCustomerOrderById completed successfully for Order: {}", orderId);
        // Single-order context — the per-call DB query inside convertToDTO(Orders) is
        // acceptable here
        return orderMapper.convertToDTO(order);
    }

    @Override
    @Transactional
    public OrderDTO cancelOrder(UUID orderId, String email) {
        logger.info("Processing cancelOrder for Order: {}, Customer: {}", orderId, email);
        Orders order = ordersRepository.findByIdWithLock(orderId)
                .orElseThrow(() -> {
                    logger.warn("Order not found: {}", orderId);
                    return new OrderNotFoundException("Order not found: " + orderId);
                });

        orderValidator.validateOrderOwnership(order, email);
        orderValidator.validateOrderCancellation(order);

        OrderStatusLookup cancelledStatus = orderValidator.getStatusOrThrow(OrderStatus.CANCELLED.name());
        orderInventoryManager.handleInventoryUpdate(order, OrderStatus.valueOf(order.getStatus().getStatusName()),
                OrderStatus.CANCELLED);

        order.setStatus(cancelledStatus);
        ordersRepository.save(order);

        eventPublisher.publishEvent(new EmailDispatchEvent(
                email,
                "Order Status Update: " + OrderStatus.CANCELLED.name(),
                "order-status",
                order.getCustomer().getOrgId(),
                java.util.Map.of(
                        "name", order.getCustomer().getFirstName() != null
                                ? order.getCustomer().getFirstName()
                                        + (order.getCustomer().getLastName() != null ? " "
                                                + order.getCustomer().getLastName() : "")
                                : order.getCustomer().getAppUser().getEmail(),
                        "orderId", order.getOrderId(),
                        "status", OrderStatus.CANCELLED.name())));

        logger.info("cancelOrder completed successfully for Order: {}", orderId);
        // Single-order context — the per-call DB query inside convertToDTO(Orders) is
        // acceptable here
        return orderMapper.convertToDTO(order);
    }

    @Override
    @Transactional(readOnly = true)
    public OrderDTO getOrderById(UUID orderId) {
        logger.info("Processing getOrderById for Order: {}", orderId);
        Orders order = getOrderOrThrow(orderId);
        logger.info("getOrderById completed successfully for Order: {}", orderId);
        // Single-order context — the per-call DB query inside convertToDTO(Orders) is
        // acceptable here
        return orderMapper.convertToDTO(order);
    }

    @Override
    @Transactional
    public OrderDTO updateOrderStatus(UUID orderId, OrderStatusUpdateDTO statusUpdate) {
        logger.info("Processing updateOrderStatus for Order: {}", orderId);
        return transitionHelper.updateOrderInternal(orderId, statusUpdate.getNewStatus());
    }

    @Override
    public BulkOrderUpdateResultDTO updateOrdersStatus(List<BulkOrderStatusUpdateDTO> updates) {
        logger.info("Processing updateOrdersStatus for {} orders", updates.size());
        List<OrderDTO> successes = new ArrayList<>();
        List<BulkOrderFailureDTO> failures = new ArrayList<>();

        for (BulkOrderStatusUpdateDTO update : updates) {
            try {
                OrderDTO result = transitionHelper.updateOrderInternal(
                        update.getOrderId(), update.getNewStatus());
                successes.add(result);
            } catch (OrderNotFoundException | InvalidOperationException | InsufficientStockException e) {
                logger.error("Bulk update failed for Order: {}: {}", update.getOrderId(), e.getMessage());
                failures.add(new BulkOrderFailureDTO(update.getOrderId(), e.getMessage()));
            }
        }

        logger.info("updateOrdersStatus completed: {} successes, {} failures",
                successes.size(), failures.size());
        return new BulkOrderUpdateResultDTO(successes, failures);
    }

    private Map<UUID, List<OrderItem>> fetchItemsMap(List<Orders> orders) {
        List<UUID> orderIds = orders.stream()
                .map(Orders::getOrderId)
                .collect(Collectors.toList());

        return orderItemRepository.findByOrderOrderIdIn(orderIds)
                .stream()
                .collect(groupingBy(item -> item.getOrder().getOrderId()));
    }

    private Orders getOrderOrThrow(UUID orderId) {
        return ordersRepository.findById(orderId)
                .orElseThrow(() -> {
                    logger.warn("Order not found: {}", orderId);
                    return new OrderNotFoundException("Order not found: " + orderId);
                });
    }
}
